graph/urls.py
from django.urls import path
from .views import GraphView

app_name = 'graph'
urlpatterns = [
    path('', GraphView.as_view(), name='graph'),
]

knowledge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('searching/', include('searching.urls', namespace='searching')),
    path('analysis/', include('analysis.urls', namespace='analysis')),
    path('keyPhrase/', include('keyPhrase.urls', namespace='keyPhrase')),
    path('graph/', include('graph.urls', namespace='graph')),
    path('upload/', include('upload.urls', namespace='upload')),
]

upload/urls.py
from django.urls import path
from .views import UploadView

app_name = 'upload'
urlpatterns = [
    path('', UploadView.as_view(), name='upload'),
]

upload/models.py
from django.db import models

# Create your models here.

upload/forms.py
from django import forms

class UploadFileForm(forms.Form):
    # file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    urls = forms.CharField(label="urls", widget=forms.Textarea(attrs={"rows":50, "cols":100}))

upload/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render
from newspaper import Article

from .forms import UploadFileForm
from searching.views import SearchView

# Create your views here.
from django.views.generic import TemplateView
from index.models import News, Author, Parent, Children, keyInformation
from . import forms


class UploadView(TemplateView):
    template_name = "upload/index.html"

    def handle_uploaded_file(f):
        with open('some/file/name.txt', 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)

    def get(self, request):
        form = UploadFileForm()
        return render(request, self.template_name)

    def post(self, request):
        form = UploadFileForm(request.POST)
        # files = request.FILES.getlist('file_field')
        if form.is_valid():
            urls = form.cleaned_data['urls']
            urls = urls.split(',')
            for url in urls:
                article = Article(url, language="zh")
                article.download()
                SearchView.scrapy(self, article)

        #     for f in files:
        #         ...  # Do something with each file.
            return render(request, self.template_name)
        else:
            return render(request, self.template_name)

upload/templates/upload/index.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8"/>
    <title>Mini Ajax File Upload Form</title>

    <!-- Google web fonts -->
    <link href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel='stylesheet'/>

    <!-- The main CSS file -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"/>
</head>

<body>

{#<form id="upload" method="post" enctype="multipart/form-data">#}
{#    {% csrf_token %}#}
{#    <div id="drop">#}
{#        Drop Here#}
{##}
{#        <a>Browse</a>#}
{#        <input id="file_field" type="file" name="file_field" multiple/>#}
{#    </div>#}
{#    <ul>#}
{#        <!-- The file uploads will be shown here -->#}
{#    </ul>#}
{##}
{#</form>#}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <textarea name="urls" cols="100" rows="50" required id="id_urls"></textarea>
    </div>
    <div class="input-field third-wrap">
        <button class="btn-search" type="submit">Search</button>
    </div>
</form>

<div id="tzine-actions">

    <a id="tzine-download" href="http://tutorialzine.com/2013/05/mini-ajax-file-upload-form/"
       title="Download This Example!">Start</a>
</div>

<!-- JavaScript Includes -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{% static 'assets/js/jquery.knob.js' %}"></script>

<!-- jQuery File Upload Dependencies -->
<script src="{% static 'assets/js/jquery.ui.widget.js' %}"></script>
<script src="{% static 'assets/js/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'assets/js/jquery.fileupload.js' %}"></script>

<!-- Our main JS file -->
<script src="{% static 'assets/js/script.js' %}"></script>


<!-- Only used for the demos. Please ignore and remove. -->
<script src="http://cdn.tutorialzine.com/misc/enhance/v1.js" async></script>

</body>
</html>

upload/templates/upload/upload.html
<!--http://tutorialzine.com/2013/05/mini-ajax-file-upload-form/-->

<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8"/>
    <title>Mini Ajax File Upload Form</title>

    <!-- Google web fonts -->
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel='stylesheet'/>

    <!-- The main CSS file -->
    <link href="{% static 'upload/style.css' %}" rel="stylesheet"/>
</head>

<body>
<form id="upload" method="post">
    {% csrf_token %}
    <div id="drop">
                Drop Here

        <a>Browse</a>
        <input type="file" name="upl" multiple/>
    </div>
    <div class="inner-form">
        <div class="input-field first-wrap">
            <input id="search_keys" type="text" name="search_keys" maxlength="100"
                   placeholder="What are you looking for?"
                   required>
        </div>
        <div class="input-field first-wrap">
            <input id="search_weight" type="text" name="search_weight" maxlength="100"
                   placeholder="What are you looking for?"
                   required>
        </div>
        <div class="input-field third-wrap">
            <button class="btn-search" type="submit">Search</button>
        </div>
    </div>
</form>

<form id="upload" method="post" action="upload.php" enctype="multipart/form-data">
    <div id="drop">
        Drop Here

        <a>Browse</a>
        <input type="file" name="upl" multiple/>
    </div>

    <ul>
        <!-- The file uploads will be shown here -->
    </ul>

</form>

<!-- JavaScript Includes -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="assets/js/jquery.knob.js"></script>

<!-- jQuery File Upload Dependencies -->
<script src="assets/js/jquery.ui.widget.js"></script>
<script src="assets/js/jquery.iframe-transport.js"></script>
<script src="assets/js/jquery.fileupload.js"></script>

<!-- Our main JS file -->
<script src="assets/js/script.js"></script>

</body>
</html>