analysis/urls.py
from django.urls import path
from .views import AnalysisView

app_name = 'analysis'
urlpatterns = [
    path('', AnalysisView.as_view(), name='analysis'),
]

graph/urls.py
from django.urls import path
from .views import GraphView

app_name = 'graph'
urlpatterns = [
    path('', GraphView.as_view(), name='graph'),
]

knowledge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('searching/', include('searching.urls', namespace='searching')),
    path('analysis/', include('analysis.urls', namespace='analysis')),
    path('keyPhrase/', include('keyPhrase.urls', namespace='keyPhrase')),
    path('graph/', include('graph.urls', namespace='graph')),
    path('upload/', include('upload.urls', namespace='upload')),
]

analysis/models.py
from django.db import models

# Create your models here.

analysis/forms.py
from django import forms


class AnalysisForm(forms.Form):
    article = forms.CharField(widget=forms.Textarea, label='article')

analysis/views.py
import nltk
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView
from nltk import word_tokenize, PorterStemmer, sent_tokenize
from nltk.corpus import stopwords

from analysis.forms import AnalysisForm

class AnalysisView(TemplateView):
    template_name = "analysis/analysis.html"

    def create_frequency_table(self, text_string):

        stopWords = set(stopwords.words("english"))
        words = word_tokenize(text_string)
        ps = PorterStemmer()

        freqTable = dict()
        for word in words:
            word = ps.stem(word)
            if word in stopWords:
                continue
            if word in freqTable:
                freqTable[word] += 1
            else:
                freqTable[word] = 1

        return freqTable

    def score_sentences(self, sentences, freqTable):
        sentenceValue = dict()

        for sentence in sentences:
            word_count_in_sentence = (len(word_tokenize(sentence)))
            for wordValue in freqTable:
                if wordValue in sentence.lower():
                    if sentence[:10] in sentenceValue:
                        sentenceValue[sentence[:10]] += freqTable[wordValue]
                    else:
                        sentenceValue[sentence[:10]] = freqTable[wordValue]

            sentenceValue[sentence[:10]] = sentenceValue[sentence[:10]] // word_count_in_sentence

        return sentenceValue

    def find_average_score(self, sentenceValue):
        sumValues = 0
        for entry in sentenceValue:
            sumValues += sentenceValue[entry]

        # Average value of a sentence from original text
        average = int(sumValues / len(sentenceValue))

        return average

    def generate_summary(self, sentences, sentenceValue, threshold):
        sentence_count = 0
        summary = ''

        for sentence in sentences:
            if sentence[:10] in sentenceValue and sentenceValue[sentence[:10]] > (threshold):
                summary += " " + sentence
                sentence_count += 1

        return summary

    def get(self, request):  # 1 Create the word frequency table
        return render(request, self.template_name)


    def post(self, request):
        form = AnalysisForm(request.POST)
        if form.is_valid():
            article = form.cleaned_data['article']
            freq_table = self.create_frequency_table(article)

            '''
            We already have a sentence tokenizer, so we just need 
            to run the sent_tokenize() method to create the array of sentences.
            '''

            # 2 Tokenize the sentences
            sentences = sent_tokenize(article)

            # 3 Important Algorithm: score the sentences
            sentence_scores = self.score_sentences(sentences, freq_table)

            # 4 Find the threshold
            threshold = self.find_average_score(sentence_scores)

            # 5 Important Algorithm: Generate the summary
            summary = self.generate_summary(sentences, sentence_scores, 1.5 * threshold)

            content = {"summary": summary}

            return render(request, self.template_name, content)

        else:
            form = AnalysisForm()
        return render(request, self.template_name)

analysis/templates/analysis/analysis.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'analysis/analysis.scss' %}"/>
</head>
<body>

{#<div id="wrapper">#}
{##}
{#    <form id="paper" method="post" action="">#}
{#        {% csrf_token %}#}
{#        <div id="margin">Title: <input id="title" type="text" name="title"></div>#}
{#        <textarea placeholder="Enter something funny." id="text" name="text" rows="4"#}
{#                  style="overflow: hidden; word-wrap: break-word; resize: none; height: 160px; "></textarea>#}
{#        <br>#}
{#        <input id="button" type="submit" value="Create">#}
{##}
{#    </form>#}
{##}
{#</div>#}

<div class="container">
    <div class="form form-stacked">
        <div class="form-block">
            <form id="paper" method="post" action="">
                {% csrf_token %}
                <textarea
                        placeholder="Ask a programming question or share a tip with other developers. Markdown is supported."
                        class="textarea-tall" name="article" cols="200" rows="60" id="id_article"></textarea>

                <input id="button" type="submit" value="Create">#}
            </form>
        </div>
    </div>
    {{ summary }}
</div>

<script src="{% static 'analysis/analysis.coffee' %}">
</script>
</body>

</html>